name: Delivery
on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout a branch
        uses: actions/checkout@v3
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: cache configured workspace for dependant jobs
        run: tar --totals --create --file workspace.tar ./
      - name: share prepared workspace with other jobs
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: workspace.tar

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - name: download prepared workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
      - name: restore workspace from archive
        run: tar --totals --extract --file workspace.tar && rm --force workspace.tar
      - name: build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
