name: Pull-Request Health Checks
on: [pull_request]

env:
  CACHE_KEY: CACHE__NODE_MODULES

jobs:
  install:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: application/node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('application/package-lock.json') }}
      - name: install dependencies
        run: npm ci
        working-directory: application

  lint:
    name: check linting
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: get node_modules
        uses: actions/cache@v1
        with:
          path: application/node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('application/package-lock.json') }}

      - name: lint via TSLint
        run: npm run lint:inspect
        working-directory: application

  formatter:
    name: check formatting
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: get node_modules
        uses: actions/cache@v1
        with:
          path: application/node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('application/package-lock.json') }}

      - name: lint via Prettier
        run: npm run prettier:check
        working-directory: application

  build:
    name: check build
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: get node_modules
        uses: actions/cache@v1
        with:
          path: application/node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('application/package-lock.json') }}

      - name: build static files
        run: npm run build
        working-directory: application
