name: labeler
on: [pull_request]

jobs:
  triage:
    name: label pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/configurations/pr-labeler.yaml
